version: "3"

services:
  app:
    container_name: todo-container
    build: .
    depends_on:
      - database
    ports:
      - "8888:8972"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://database:3306/sample?useUnicode=true
      SPRING_DATASOURCE_USERNAME: todo_user
      SPRING_DATASOURCE_PASSWORD: todo_passwd
    restart: always
    links:
      - database
    platform: linux/amd64
    
  database:
    image: mariadb:11.3.2
    container_name: mariadb-container
    environment:
      MARIADB_ROOT_PASSWORD: 1234
      MARIADB_USER: todo_user
      MARIADB_PASSWORD: todo_passwd
      MARIADB_DATABASE: sample
    volumes:
      - ./docker/init-db-script:/docker-entrypoint-initdb.d
    ports:
      - "6033:3306"
