# # port 
server:
    port: 8888

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/encore
    username: todo_user
    password: todo_passwd

mybatis:
  mapper-locations: mapper/*.xml